"""Add created_by_id to tickets

Revision ID: b40081731122
Revises: f1f88db56567
Create Date: 2026-02-06 16:04:35.308910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40081731122'
down_revision: Union[str, Sequence[str], None] = 'f1f88db56567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'created_by_id')
    # ### end Alembic commands ###
